name: sized_box_extension
description: An extension for Flutter's SizedBox widget to make it easier to create boxes with specific widths and heights.
version: 0.0.1
homepage: https://github.com/Hikmatullohprogramist/sized_box_extension
repository: https://github.com/Hikmatullohprogramist/sized_box_extension
environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true